name: contact
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.12*
  - pip>=24.2
  - gdal
  - django>= 5.0, < 6.0
  - django-filter>=23.5.0
  - djangorestframework>=3.14.0 
  - djangorestframework-gis==1.0
  - django-cors-headers==4.3.1
  - gunicorn==21.2.0
  - psycopg2-binary==2.9.9
  - pip:
    - django-admin-interface==0.28.3
    - django-cleanup==8.0.0
    - django-admin-autocomplete-filter==0.7.1
    - django-admin-numeric-filter==0.1.9
